[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/rebt"
  to = "/.netlify/functions/rebt_api"
  status = 200

[[redirects]]
  from = "/api/tts"
  to = "/.netlify/functions/tts_api"
  status = 200
